# Do not change this setting
file-version: 1

# Language of the plugin.
# For more information: https://github.com/nickuc/OpeNLogin/blob/master/docs/lang.md
languageFile: 'messages_en.yml'

# The plugin will be able to send advertisements to the administrators.
# For example: nLogin recommendation.
allow-advertising: true

# Fork-specific features and notes.
Forks:
  # Forces players to spawn before login, then returns them to their last location.
  spawn-before-login-return-last-location: true

# Security system related settings.
Security:
  # Amount of time for a player to log in/register (set in seconds).
  time-to-login: 45

  password:
    # Small password size.
    small: 5

    # Size for big passwords.
    large: 15
