#    ___                __  __
#   /___\_ __   ___  /\ \ \/ /  ___   __ _(_)_ __
#  //  // '_ \ / _ \/  \/ / /  / _ \ / _` | | '_ \
# / \_//| |_) |  __/ /\  / /__| (_) | (_| | | | | |
# \___/ | .__/ \___\_\ \/\____/\___/ \__, |_|_| |_|
#       |_|                          |___/

# Official website: https://www.nickuc.com
# Discord: https://www.nickuc.com/discord

# Do not change this setting
file-version: 1

# Language of the plugin.
# For more information: https://github.com/nickuc/OpeNLogin/blob/master/docs/lang.md
languageFile: 'messages_en.yml'

# The plugin will be able to send advertisements to the administrators.
# For example: nLogin recommendation.
allow-advertising: true

# Fork-specific features and notes.
Forks:
  # Requires ProtocolLib to hide player inventory before login.
  # Install ProtocolLib from https://www.spigotmc.org/resources/protocollib.1997/
  hide-inventory-before-login: true
  # Forces players to spawn before login, then returns them to their last location.
  spawn-before-login-return-last-location: true

# Security system related settings.
Security:
  # Amount of time for a player to log in/register (set in seconds).
  time-to-login: 45

  password:
    # Small password size.
    small: 5

    # Size for big passwords.
    large: 15
